#!/usr/bin/env node
const hardlink = require('./index')
const minimist = require('minimist')
const args = minimist(process.argv.slice(2), { alias: { mode: 'm' } })
const [cwd, dest, pattern = '**'] = args._
hardlink(pattern, dest, { cwd, copyMode: args.mode })
